//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Action/UI/InventoryInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InventoryInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InventoryInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InventoryInputAction"",
    ""maps"": [
        {
            ""name"": ""OpneInven"",
            ""id"": ""2907b442-e75c-447c-97ce-9324d64ad05c"",
            ""actions"": [
                {
                    ""name"": ""Inven"",
                    ""type"": ""Button"",
                    ""id"": ""4f161c18-5fe3-408e-8d18-901d3b77fc59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9998cf2f-b003-4d14-8af1-9e6da3226e12"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68813578-668d-4fab-b14b-1c3062749cfe"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OpneInven
        m_OpneInven = asset.FindActionMap("OpneInven", throwIfNotFound: true);
        m_OpneInven_Inven = m_OpneInven.FindAction("Inven", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OpneInven
    private readonly InputActionMap m_OpneInven;
    private List<IOpneInvenActions> m_OpneInvenActionsCallbackInterfaces = new List<IOpneInvenActions>();
    private readonly InputAction m_OpneInven_Inven;
    public struct OpneInvenActions
    {
        private @InventoryInputAction m_Wrapper;
        public OpneInvenActions(@InventoryInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Inven => m_Wrapper.m_OpneInven_Inven;
        public InputActionMap Get() { return m_Wrapper.m_OpneInven; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OpneInvenActions set) { return set.Get(); }
        public void AddCallbacks(IOpneInvenActions instance)
        {
            if (instance == null || m_Wrapper.m_OpneInvenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OpneInvenActionsCallbackInterfaces.Add(instance);
            @Inven.started += instance.OnInven;
            @Inven.performed += instance.OnInven;
            @Inven.canceled += instance.OnInven;
        }

        private void UnregisterCallbacks(IOpneInvenActions instance)
        {
            @Inven.started -= instance.OnInven;
            @Inven.performed -= instance.OnInven;
            @Inven.canceled -= instance.OnInven;
        }

        public void RemoveCallbacks(IOpneInvenActions instance)
        {
            if (m_Wrapper.m_OpneInvenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOpneInvenActions instance)
        {
            foreach (var item in m_Wrapper.m_OpneInvenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OpneInvenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OpneInvenActions @OpneInven => new OpneInvenActions(this);
    public interface IOpneInvenActions
    {
        void OnInven(InputAction.CallbackContext context);
    }
}
